---
- name: upgrade
  become: yes
  action: apt update_cache=yes upgrade=yes

- name: ensure the system encoding is utf-8
  become: yes
  template: src=locale dest=/etc/default/locale owner=root group=root mode=644

- name: install dependencies 
  become: yes
  action: "apt pkg={{ item }} state=present"
  with_items: "{{ common_setup.packages }}"
