---
- name: upgrade
  action: apt update_cache=yes upgrade=yes

- name: ensure the system encoding is utf-8
  sudo: yes
  template: src=locale dest=/etc/default/locale owner=root group=root mode=644

- name: install dependencies 
  action: apt pkg={{ item }} state=installed
  with_items: {{ common_setup.packages }}
